<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>TPE entrega 2</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark justify-content-center">
            <ul class="nav nav-underline">
                
                <li class="nav-item">
                    <a class="nav-link" href="cerrarSesion">cerrar sesion</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="miPerfil">mi perfil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="verSuscripciones">ver suscripciones</a>
                </li>
            </ul>
            </nav>
    </header>