<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <base href="<?php echo BASE_URL ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>TPE entrega 2</title>
</head>

<body>
  <h1>Iniciar Sesion</h1>
  <form action="iniciar" method="POST" class="mx-5">
    <div class="mb-3">
      <label class="form-label">Email</label>
      <input type="email" class="form-control" name="email">
    </div>
    <div class="mb-3">
      <label class="form-label">contraseña</label>
      <input type="password" class="form-control" name="contraseña">
    </div>
    <?php if ($error) : ?>
      <h2><?= $error ?></h2>
    <?php endif ?>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  <h2><a href="registro">Registrarse</a></h2>