<!DOCTYPE html>
<html>

<form action="registrar" method="POST">
    <input type="text" name="nombre" placeholder="ingrese su nombre" require>
    <input type="email" name="email-registro" placeholder="Ingrese su Email" require>
    <input type="password" name="contraseña-registro" placeholder="Ingrese su contraseña" require>
    <input type="number" name="suscripcion" placeholder="ingrese su tipo de suscripocion" require>
    <button type="submit">registrar</button>
</form>

</html>